apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-classifier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: text-classifier
  template:
    metadata:
      labels:
        app: text-classifier
    spec:
      containers:
      - name: text-classifier
        image: toliaba/text-classifier:latest  # Замініть на ваш Docker-образ
        ports:
        - containerPort: 8080
