name: Blue-Green Deployment to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout репозиторій
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Логін у Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t toliaba/text-classifier:${{ github.sha }} .
          docker push toliaba/text-classifier:${{ github.sha }}

      # 4. Set up gcloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT }}

      # 5. Authenticate kubectl
      - name: Authenticate kubectl
        run: |
          gcloud container clusters get-credentials autopilot-cluster-1 --region us-central1 --project ${{ secrets.GCP_PROJECT }}

      # 6. Blue Deployment
      - name: Deploy Blue Version
        run: |
          kubectl apply -f k8s/deployment.yml
          kubectl set image deployment text-classifier text-classifier=toliaba/text-classifier:${{ github.sha }}

      # 7. Wait for Deployment
      - name: Wait for Blue Deployment
        run: |
          kubectl rollout status deployment text-classifier

      # 8. Green Testing
      - name: Test Blue Deployment
        run: |
          # Add any application-specific testing logic here
          echo "Testing Blue Deployment Successful"

      # 9. Swap Traffic
      - name: Swap Traffic to Blue Deployment
        run: |
          kubectl apply -f k8s/service.yml
